Rework #to_s to eliminate Ruby warning
Using the ISO8601::DateTime#to_s with warnings enabled produced
the following warning:

`iso8601-0.12.1/lib/iso8601/date_time.rb:52: warning: too many arguments for format string`

This is because the #atoms method is returning an array of 7
elements, which turns into 7 arguments for the `format` method.
The current format passed only uses 5 arguments. This change
adjusts the format passed to use all 7 arguments.